name: health_analytics
version: 2.0.0
config-version: 2
profile: health_analytics

model-paths:
  - models
macro-paths:
  - macros

models:
  health_analytics:
    silver_staging:
      +schema: SILVER_STAGING
    silver_canonical:
      +schema: SILVER_CANONICAL

clean-targets:
  - target
  - dbt_packages
